name: Run Telegram Bot

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 0 * * *' # Daily at midnight (optional)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the latest LTS version

      - name: Install dependencies
        run: npm install

      - name: Run the bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} # Add your bot token as a secret
        run: node index.js
